[project]
name = "omni"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Karan Ravindra", email = "21176108+karanravindra@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.2.0",
    "ipywidgets>=8.1.8",
    "matplotlib>=3.10.8",
    "ollama>=0.6.1",
    "pandas>=3.0.0",
    "torch>=2.10.0",
    "torchinfo>=1.8.0",
    "tqdm>=4.67.3",
]

[project.scripts]
omni = "omni:main"

[build-system]
requires = ["uv_build>=0.9.26,<0.10.0"]
build-backend = "uv_build"
